version: "3.8"
networks:
  web-network:
    driver: bridge
services:
  postgres:
    build: db/
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web-network
  django:
    build: .
    container_name: travel-app
    ports:
      - "8000:8000"
    networks:
      - web-network
    depends_on:
      - postgres
volumes:
  postgres_data:
